### ISSUE TITLE
Resource Pack Textures/ model not loading

### ISSUE THREAD

**Issue by SanjivanM** [keotl/mcdisc-resource-builder#11]
DISCLAIMER: Didn't know where to put this, sorry!

So I've created my resource pack, and loaded it into Minecraft, but the on ground/inventory model don't load (they have the checkered pattern)

I've attached the resource pack, and the latest.log are below
[SM_Discs.zip (Resource Pack with custom texture)](https://github.com/keotl/mcdisc-resource-builder/files/4114573/SM_Discs.zip)
[latest.log](https://github.com/keotl/mcdisc-resource-builder/files/4114581/latest.log)

**Comment by keotl** [comment]
This is the right place to post this kind of issue! 

By default, mcdisc looks at the "id" property to select one of the vanilla minecraft textures. Since you want to use one of your custom textures, you have to explicitly indicate which **texture id** mcdisc should load for your disc. I pasted what your config json should look like below. Notice the "texture" property. 

```json
[
    {
        "id": 1,
        "minecraftId": "item.ts.1",
        "url": "https://www.youtube.com/watch?v=IdneKLhsWOQ",
        "name": "Wildest Dreams",
        "artist": "Taylor Swift",
        "soundId": "sound.ts.1",
        "texture": "mcdisc:ts_wd"
    }
]
```
I also updated your /assets/mcdisc/lang/en_us.lang file to look like this:
```
item.record.item.ts.1.desc=Taylor Swift - Wildest Dreams
```
The item.ts.1 part should match your config file, otherwise you won't see the text correctly displayed. (The resource pack builder should take care of this automatically.)

Cheers

**Comment by SanjivanM** [comment]
does the name of the model JSON file have to be the same as the minecraft ID? And I'm assuming that the "layer0" in the model JSON has to be the name of the texture file, like items in modding?
ex. for a texture named texture_1.png
`...
"layer0": "mcdisc:items/texture_1"
...`
or should it be the minecraft ID?

**Comment by SanjivanM** [comment]
Figured it out (somehow) :P
